### ISSUE TITLE
Are this repo really *Discountinued*

### ISSUE THREAD

**Issue by nielsonsantana** [bitlabstudio/django-registration-email#37]
Hi, are this repo Discontinued?

**Comment by nielsonsantana** [comment]
There any guide to migrate to django-allauth? How you did it?

**Comment by Tyrdall** [comment]
There's no need to migrate to allauth, since you can keep your user model. Just remove this app and follow all steps in the allauth docs: http://django-allauth.readthedocs.org/en/latest/installation.html

**Comment by nielsonsantana** [comment]
Thanks @Tyrdall!!
