### ISSUE TITLE
Errno 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by uyak** [bitlabstudio/django-registration-email#8]
hi i have this working on local machine when im on accounts/register and try create a new user i get this error
_^_***************************+

error at /accounts/register/

[Errno 10061] No connection could be made because the target machine actively refused it

Request Method:     POST
Request URL:    http://127.0.0.1:8000/accounts/register/
Django Version:     1.5
Exception Type:     error
Exception Value:    

[Errno 10061] No connection could be made because the target machine actively refused it

Exception Location:     C:\Python27\lib\socket.py in create_connection, line 571
Python Executable:  C:\Python27\python.exe
Python Version:     2.7.3
Python Path:    

['C:\Users\ujake\impromusic\impromusic',
 'C:\Python27\lib\site-packages\distribute-0.6.35-py2.7.egg',
 'C:\Python27\lib\site-packages\django_audiotracks-0.2.1-py2.7.egg',
 'C:\Python27\lib\site-packages\mutagen-1.20-py2.7.egg',
 'C:\Python27\lib\site-packages\django_registration_email-0.5-py2.7.egg',
 'C:\Windows\system32\python27.zip',
 'C:\Python27\DLLs',
 'C:\Python27\lib',
 'C:\Python27\lib\plat-win',
 'C:\Python27\lib\lib-tk',
 'C:\Python27',
 'C:\Python27\lib\site-packages',
 'C:\Python27\lib\site-packages\PIL',
 'C:\Python27\lib\site-packages\setuptools-0.6c11-py2.7.egg-info']

Server time:    Tue, 26 Mar 2013 03:55:14 +0100
Traceback Switch to copy-and-paste view

```
C:\Python27\lib\site-packages\django\core\handlers\base.py in get_response

                            response = callback(request, *callback_args, **callback_kwargs)

    ...
▶ Local vars
C:\Python27\lib\site-packages\registration\views.py in register

                new_user = backend.register(request, **form.cleaned_data)

    ...
▶ Local vars
C:\Python27\lib\site-packages\registration\backends\default\__init__.py in register

                                                                        password, site)

    ...
▶ Local vars
C:\Python27\lib\site-packages\django\db\transaction.py in inner

                    return func(*args, **kwargs)

    ...
▶ Local vars
C:\Users\ujake\impromusic\impromusic\impromusic\apps\registration\models.py in create_inactive_user

                registration_profile.send_activation_email(site)

    ...
▶ Local vars
C:\Users\ujake\impromusic\impromusic\impromusic\apps\registration\models.py in send_activation_email

            self.user.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)

    ...
▶ Local vars
C:\Python27\lib\site-packages\django\contrib\auth\models.py in email_user

            send_mail(subject, message, from_email, [self.email])

    ...
▶ Local vars
C:\Python27\lib\site-packages\django\core\mail\__init__.py in send_mail

                            connection=connection).send()

    ...
▶ Local vars
C:\Python27\lib\site-packages\django\core\mail\message.py in send

            return self.get_connection(fail_silently).send_messages([self])

    ...
▶ Local vars
C:\Python27\lib\site-packages\django\core\mail\backends\smtp.py in send_messages

                new_conn_created = self.open()

    ...
▶ Local vars
C:\Python27\lib\site-packages\django\core\mail\backends\smtp.py in open

                                               local_hostname=DNS_NAME.get_fqdn())

    ...
▶ Local vars
C:\Python27\lib\smtplib.py in __init__

                (code, msg) = self.connect(host, port)

    ...
▶ Local vars
C:\Python27\lib\smtplib.py in connect

            self.sock = self._get_socket(host, port, self.timeout)

    ...
▶ Local vars
C:\Python27\lib\smtplib.py in _get_socket

            return socket.create_connection((port, host), timeout)

    ...
▶ Local vars
C:\Python27\lib\socket.py in create_connection

            raise err

    ...
▶ Local vars 
```

---

Do i have to configure the email server on settings.py for use your app?

**Comment by verkko** [comment]
I have tired all the above, still am getting an error. Can some one help me here.


![4](https://user-images.githubusercontent.com/2504880/79246202-c0057a00-7e96-11ea-86c0-aad8cf468a8c.PNG)

![2](https://user-images.githubusercontent.com/2504880/79246170-b9770280-7e96-11ea-9a8c-4160ad25cece.PNG)
[unames.txt](https://github.com/bitlabstudio/django-registration-email/files/4476361/unames.txt)

![3](https://user-images.githubusercontent.com/2504880/79246183-bc71f300-7e96-11ea-9367-ece757bb2940.PNG)



`
![1](https://user-images.githubusercontent.com/2504880/79246152-b4b24e80-7e96-11ea-9e79-004674f7ade3.PNG)
`

**Comment by verkko** [comment]
I have tried everything as above. Still am getting error. Can some one please help me. 
![1](https://user-images.githubusercontent.com/2504880/79246560-f80cbd00-7e96-11ea-9338-c086370fc4de.PNG)
![2](https://user-images.githubusercontent.com/2504880/79246579-fe9b3480-7e96-11ea-8a6f-4f1f45d25339.PNG)
![3](https://user-images.githubusercontent.com/2504880/79246600-05c24280-7e97-11ea-8f5d-98639133f6b7.PNG)
![4](https://user-images.githubusercontent.com/2504880/79246618-0c50ba00-7e97-11ea-9c4e-6fde19a2514e.PNG)
